CREATE TABLE [dbo].[Error]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Message] NVARCHAR(MAX) NOT NULL,
	[Class] NVARCHAR(MAX) NULL,
	[Method] NVARCHAR(MAX) NULL,
    [DateOccured] DATETIME NOT NULL DEFAULT GETDATE(),

	CONSTRAINT [PK_Error] PRIMARY KEY ([Id])
)
