CREATE TABLE [dbo].[QuestionTag]
(
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), 
    [QuestionId] UNIQUEIDENTIFIER NOT NULL, 
    [TagId] UNIQUEIDENTIFIER NOT NULL

	CONSTRAINT [PK_QuestionTag] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_QuestionTag_Question] FOREIGN KEY ([QuestionId]) REFERENCES [Question]([Id]),
	CONSTRAINT [FK_QuestionTag_Tag] FOREIGN KEY ([TagId]) REFERENCES [Tag]([Id])
)
