CREATE TABLE [dbo].[User]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[FirebaseId] NVARCHAR(50) NULL,  -- FIX THIS AFTER DEBUGGING SHIT!!! SHOULD BE NOT NULL!
    [EmailAddress] NVARCHAR(50) NOT NULL UNIQUE, 
    [DisplayName] NVARCHAR(50) NOT NULL, 
    [PhotoUrl] NVARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 0,
    [JoinedOn] DATETIME NOT NULL DEFAULT GETDATE()

	CONSTRAINT [PK_User] PRIMARY KEY ([Id])
)
