CREATE TABLE [dbo].[User]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
	[FirebaseId] NVARCHAR(50) NULL,  -- FIX THIS AFTER DEBUGGING SHIT!!! SHOULD BE NOT NULL!
    [EmailAddress] NVARCHAR(50) NOT NULL UNIQUE, 
    [DisplayName] NVARCHAR(50) NOT NULL, 
    [PhotoUrl] NVARCHAR(50) NULL,
	[IsActive] BIT NOT NULL DEFAULT 0,
    [JoinedOn] DATETIME NOT NULL DEFAULT GETDATE()
)
